---
- name: Update package lists
  hosts: clients
  become: yes
  tasks:
    - name: Update package lists on Debian-based systems
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package lists on Red Hat-based systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
