---
- name: Distribute SSH keys to clients
  hosts: firewall, clients
  become: yes
  tasks:
    - name: Ensure ~/.ssh directory exists on the remote host
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
    
    - name: Copy SSH public key to authorized_keys on remote host
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        mode: '0600'
      when: ansible_user in ['admin', 'lucian']
