---
- name: Install Docker on Debian, Ubuntu, CentOS, and Fedora
  hosts: clients
  become: yes

  tasks:
    # Uninstall conflicting packages for all distributions
    - name: Remove conflicting packages
      block:
        - name: Remove conflicting packages on Debian/Ubuntu
          ansible.builtin.shell: |
            for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
              apt remove -y $pkg
            done
          when: ansible_os_family == "Debian"

        - name: Remove conflicting packages on CentOS/Fedora
          ansible.builtin.shell: |
            dnf remove -y docker docker-client docker-client-latest docker-common \
              docker-latest docker-latest-logrotate docker-logrotate docker-selinux \
              docker-engine-selinux docker-engine
          when: ansible_os_family == "RedHat"

    # Debian-based systems
    - name: Install Docker on Debian-based systems
      block:
        - name: Add Docker GPG key and repository
          ansible.builtin.shell: |
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          args:
            creates: /etc/apt/keyrings/docker.gpg

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: yes

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
      when: ansible_os_family == "Debian"

    # Red Hat-based systems
    - name: Install Docker on Red Hat-based systems
      block:
        - name: Install dnf-plugins-core
          ansible.builtin.dnf:
            name: dnf-plugins-core
            state: present

        - name: Add Docker repository
          ansible.builtin.shell: |
            dnf config-manager --add-repo https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo
          args:
            creates: /etc/yum.repos.d/docker-ce.repo

        - name: Install Docker packages
          ansible.builtin.dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
            update_cache: yes
      when: ansible_os_family == "RedHat"

    # Start Docker service for all systems
    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    # Add user 'lucian' to the Docker group
    - name: Add user to Docker group
      ansible.builtin.user:
        name: lucian
        groups: docker
        append: yes

    # Refresh group membership
    - name: Refresh Docker group membership (optional)
      ansible.builtin.shell: newgrp docker || true
      args:
        warn: false
