---
- name: Update /etc/hosts file on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/hosts contains the correct entries
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "192.168.1.2    pfsense"
        - "192.168.1.10   centos ansible docker greenbone wazuh onion"
        - "192.168.1.11   ubuntu ldap snort suricata ids ips"
        - "192.168.1.12   fedora"
        - "192.168.1.13   debian"
        - "192.168.1.14   kali"
