---
- name: Ensure nano is installed
  hosts: clients
  become: yes
  tasks:
    - name: Install nano on Debian-based systems
      apt:
        name: nano
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install nano on RedHat-based systems
      yum:
        name: nano
        state: latest
      when: ansible_os_family == "RedHat"
