---
- name: Configure pfSense
  hosts: pfsense
  gather_facts: no
  tasks:
    - name: Set system hostname
      pfsense_hostname:
        hostname: "pfSense"
        domain: "home.arpa"

    - name: Set DNS servers
      pfsense_dns:
        servers:
          - "1.1.1.1"
          - "1.0.0.1"

    - name: Configure SSH
      pfsense_ssh:
        enabled: true

    - name: Configure NTP servers
      pfsense_ntp:
        servers:
          - "2.pfsense.pool.ntp.org"

    - name: Configure groups
      pfsense_group:
        name: "admins"
        description: "System Administrators"
        gid: 1999
        members: 
          - "0"
        privileges:
          - "page-all"

    - name: Create user admin
      pfsense_user:
        name: "admin"
        description: "System Administrator"
        group: "admins"
        uid: 0
        bcrypt_hash: "$2y$10$5FdANIdeYpRqlPDLCzaTuOr30i6hzccI3dWSn21v01.JSk6I6hOMe"

    - name: Set webgui settings
      pfsense_webgui:
        protocol: "http"
        ssl_cert_ref: "671418e57454e"
        max_procs: 2
        dashboard_columns: 2
        roaming: "enabled"

    - name: Set interface WAN
      pfsense_interface:
        name: "wan"
        enable: true
        ipaddr: "dhcp"
        block_bogons: true

    - name: Set interface LAN
      pfsense_interface:
        name: "lan"
        enable: true
        ipaddr: "192.168.100.2"
        subnet: "24"

    - name: Configure DHCP for LAN
      pfsense_dhcp:
        interface: "lan"
        enable: true
        range:
          from: "192.168.100.100"
          to: "192.168.100.200"

    - name: Configure firewall rules
      pfsense_firewall_rule:
        interface: "wan"
        protocol: "tcp"
        source: "any"
        destination:
          network: "wanip"
          port: 22
        description: "SSH access from WAN"
        action: "pass"

    - name: Add LAN SSH rule
      pfsense_firewall_rule:
        interface: "lan"
        protocol: "tcp"
        source:
          network: "192.168.100.0/24"
        destination:
          network: "(self)"
          port: 22
        description: "Allow SSH from LAN"
        action: "pass"

    - name: Add LAN HTTP rule
      pfsense_firewall_rule:
        interface: "lan"
        protocol: "tcp"
        source:
          network: "192.168.100.0/24"
        destination:
          network: "(self)"
          port: 80
        description: "LAN access to webConfigurator via HTTP"
        action: "pass"

    - name: Set cron jobs
      pfsense_cron:
        minute: "*/1"
        hour: "*"
        mday: "*"
        month: "*"
        wday: "*"
        user: "root"
        command: "/usr/sbin/newsyslog"

    # Add more tasks as needed for other settings
